name: Gods Nexus
favicon: null
layout_spectrum: 0.6087148208171129
typography_spectrum: 0.8719594592694193
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2799402573145926
  lightness: 0.5455220572184771
  saturation: 0.3096130723133683
  rhythmicContrast: 0.4880780088715255
purpose: []
